spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${servidorBD}:$3307/viajes?serverTimezone=UTC
    #url: jdbc:mysql://localhost:3307/viajes?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
server:
  port: 7000
  
eureka:
  client:
    service-url:
      defaultZone: http://${servidorEureka}:8761/eureka
     # defaultZone: http://localhost:8761/eureka
   instance:
     hostname: ${host}

